'''
/*
 * @name: rna.py
 * @author: Manu Molina
 * @version: 1.0
 * @description: 
 	Given: A DNA string tt having length at most 1000 nt.
	Return: The transcribed RNA string of tt.
 * @date: 30/11/2017 
 * @python version: 3.6.3 Anaconda
*/
'''

str = "CATTCAGGACGCGAATGCGCATAGTCTGTTAAAACACACAGCCATAAAAATCTTACACCGCGGCCCCCAGGATGTTAAACGCATACCAGCTGGTCCTAGTCAGTCCCTGATCCCTTCAGCTTTGTAGTCCGATTGCAATCTCACAGTGACAAGTCGGGCTACACATAGTAGATGCTTATAAGGACAGGATAGCTGACGCCAGAAAGTTTAAAGCATGTAGCAAGGGAAATCGCGTGAAAGCATTCGAGACGACACCATCAGTGCAAAGCTTTAGTTTCGCTGCGGTGAAGCTGTGAGATTGACGAATAGACCCCACGAGTCAGCGTAGTTGGTATATTGATCGTCGGTGAGGGCCTTGACGGTTTGCCGTTTACCGGCCATCGCTCCTGTCCTCTACTTCGCTGAAGGTTCTCTTATGTCTATCCGATTAGCGTTATGCAGTAAGACGATGTTTAGGGCAGCCCTTGTGTAGTTGATAAGAGGAGGGTGACCGTGGCGCAAAGACCGCTTAAACGATTACCCGCAGTTGTACGAAAGCAAGTATCCGCCCTGATTGTCTGTACTTATGGTGGCCCTGGATTCAAGGTTATGAGAAATGTCCTCGTGAGCCCAGTACACCATAAAATTTTAGGAGAGTCGCTGGAACCCCAAGAGCTACTATTCATATTGGCCGCACGATTGTGTGATAGCTTTACTATTTAATCCGTATTAGTTCTTGACTAGTCAATCAAGCTGACCAAGAGCATATGAACGAACTCGTAAGGGGAAGACAGGGAAAGGTTTAGTTGAGTTTGCTGCCATGTACAATGGTTTAGATATTATGGCTGGCGCTCCAACCGGGGTCACTCGCAACCTGTTCTATATAAAGTGCCAATAACACTAACCCATCGCAGCACTATCCTGCAGCAATTAGCGACCAGAACTCATTGAGCCGGTTTTCA"
print (str.replace("T", "U"))

with open("Output.txt", "w") as text_file:
    print(str.replace("T", "U"), file=text_file)
