'''
/*
 * @name: dna.py
 * @author: Manu Molina
 * @version: 1.0
 * @description: 
 	Given: A DNA string ss of length at most 1000 nt.
	Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in ss.
 * @date: 30/11/2017 
 * @python version: 3.6.3 Anaconda
*/
'''

from collections import Counter

str = "CAGAAGCGAATTAATAGCTACTCGGCGATTTCGTACTTAAGGGATTTCTATCCGGGGGGTTGTAAACGACAAGCTACCGGAACGCCATCGAACACTCCATGGCGGTGACCGCTATTGGCTCGGCGAGACAAGGAGCTGGCCCTACCTGCATATCGGTTCAGTTACAATCAGACGTATGTAGGCGAGTCGTTGTGCAAGGATACATCGTAGTTCCGTTTGTGGGAGAACACCGGCGGGTCATCTAGTACTTGCACAGACGGAGAGTGCCGCGGCCTTCCTCGCTTGTACAGGCCGTACTTAGCCCATATCACAAGCGTACTTAAGGGATGATAATCAATTCAGTACGGGTGCACGCGCCGGTCCCTGGTACCTCTTCTCAGCAGCTAGTAGGTGCAAGCCGTGATCTAATGCCTCGGTCGAGACGTCGACGTTTTTTAACGCAGTTCTTTTGTGCGCCACGACTTTCATCCGCGGCCCACGCCGGCTTCCGCTACAGAGCTAGGCAGCGTTGTGTCCCGTGGTGTCTAGTTTTTGGTAAAATCTATTAGGTAAACTAGATCTGGATAGAGCACAAGCCTAACATGGCTGGGCCGAGGATCCAAGACACGGTGTGTCGGCCAATCGGCTAGGCGTTGCGCGACAGGGAGAGTTTGAACCCAGACGGTAACTGCAATGTAATAGACTGACTTATGTAGCCCTAGTATTGAATGGCCGTGGCCTCCATGGACTGCTAAGTCCCATTCTGTGGTCTATCAGCAAGCTAACTTAGGTATTGATCGGGTTAATAAATATCATTGCGTGTCATGTGTATTTCACTCTCCATGCATAATTTTGCCTGTGGTTGATATGGCGCCCATGC"
counter = Counter(str)
print ("%s %s %s %s" % (counter['A'], counter['C'], counter['G'], counter['T']))

with open("Output.txt", "w") as text_file:
    print ("%s %s %s %s" % (counter['A'], counter['C'], counter['G'], counter['T']), file=text_file)
